// Generated by Cypress Author on 2026-10-05.
describe('SauceDemo cart', {
  baseUrl: 'https://www.saucedemo.com',
  testIsolation: true,
}, () => {
  it('Додавання двох товарів → кошик містить обрані товари', () => {
    const products = [
      { id: 'sauce-labs-backpack', name: 'Sauce Labs Backpack', price: '$29.99' },
      { id: 'sauce-labs-bike-light', name: 'Sauce Labs Bike Light', price: '$9.99' },
    ];

    cy.fixture('user').then(({ standardUser }) => {
      cy.login(standardUser.username, standardUser.password);
    });

    cy.location('pathname').should('eq', '/inventory.html');
    cy.get('[data-test="inventory-list"]').should('be.visible');
    cy.get('[data-test="shopping-cart-badge"]').should('not.exist');

    products.forEach((product, index) => {
      cy.get(`[data-test="add-to-cart-${product.id}"]`).click();
      cy.get(`[data-test="remove-${product.id}"]`)
        .should('be.visible')
        .and('have.text', 'Remove');
      cy.get('[data-test="shopping-cart-badge"]')
        .should('be.visible')
        .and('have.text', String(index + 1));
    });

    cy.get('[data-test="shopping-cart-link"]').click();

    cy.location('pathname').should('eq', '/cart.html');
    cy.contains('[data-test="title"]', /^Your Cart$/).should('be.visible');
    cy.get('[data-test="inventory-item"]').should('have.length', products.length);
    cy.get('[data-test="shopping-cart-badge"]').should('have.text', String(products.length));

    // Check each product within its own cart row, independent of display order.
    products.forEach((product) => {
      cy.contains('[data-test="inventory-item"]', product.name)
        .should('be.visible')
        .within(() => {
          cy.get('[data-test="inventory-item-name"]').should('have.text', product.name);
          cy.get('[data-test="inventory-item-price"]').should('have.text', product.price);
          cy.get('[data-test="item-quantity"]').should('have.text', '1');
          cy.get(`[data-test="remove-${product.id}"]`).should('be.visible');
        });
    });
  });
});
