// Generated by Cypress Author on 2026-10-08.
import LoginPage from '../../pages/LoginPage.js';

describe('SauceDemo logout', {
  baseUrl: 'https://www.saucedemo.com',
  testIsolation: true,
  screenshotOnRunFailure: false,
}, () => {
  const loginPage = new LoginPage();

  // Requirements R-AUTH-006, R-AUTH-007; scenario AUTH-011.
  it('Log out → clears the session and prevents reopening the inventory', () => {
    loginPage.visit();
    cy.env(['SAUCE_USER', 'SAUCE_PASSWORD']).then(({ SAUCE_USER, SAUCE_PASSWORD }) => {
      if (!SAUCE_USER || !SAUCE_PASSWORD) {
        throw new Error('Set SAUCE_USER and SAUCE_PASSWORD to a valid, unlocked SauceDemo account.');
      }
      cy.LoginPom(SAUCE_USER, SAUCE_PASSWORD);
    });
    cy.location('pathname').should('eq', '/inventory.html');
    cy.get('[data-test="inventory-list"]').should('be.visible');

    // The menu button has no data-test attribute; use its stable application ID.
    cy.get('#react-burger-menu-btn').click();
    cy.get('[data-test="logout-sidebar-link"]').should('be.visible').click();

    cy.location('pathname').should('eq', '/');
    cy.get(loginPage.loginButton).should('be.visible');
    cy.getCookie('session-username', { log: false }).should('be.null');
    cy.get('[data-test="inventory-container"]').should('not.exist');

    // The host returns 404 for this SPA route; still verify the application's guard.
    cy.visit('/inventory.html', { failOnStatusCode: false });
    cy.location('pathname').should('eq', '/');
    loginPage.errorMesagge().should('be.visible').and(
      'have.text',
      "Epic sadface: You can only access '/inventory.html' when you are logged in.",
    );
    cy.get('[data-test="inventory-container"]').should('not.exist');
  });
});
