// Generated by Cypress Author on 2026-10-08.
import LoginPage from '../../pages/LoginPage.js';

describe('SauceDemo login', {
  baseUrl: 'https://www.saucedemo.com',
  testIsolation: true,
  screenshotOnRunFailure: false,
}, () => {
  const loginPage = new LoginPage();

  const expectInventory = () => {
    cy.location('pathname').should('eq', '/inventory.html');
    cy.contains('[data-test="title"]', /^Products$/).should('be.visible');
    cy.get('[data-test="inventory-list"]').should('be.visible');
    cy.get('[data-test="inventory-item"]').should('have.length.greaterThan', 0);
    cy.get(loginPage.loginButton).should('not.exist');
  };

  beforeEach(() => {
    loginPage.visit();
    cy.env(['SAUCE_USER', 'SAUCE_PASSWORD']).then(({ SAUCE_USER, SAUCE_PASSWORD }) => {
      if (!SAUCE_USER || !SAUCE_PASSWORD) {
        throw new Error('Set SAUCE_USER and SAUCE_PASSWORD to a valid, unlocked SauceDemo account.');
      }
      cy.LoginPom(SAUCE_USER, SAUCE_PASSWORD);
    });
  });

  // Requirement R-AUTH-001; scenario AUTH-001.
  it('Submit valid credentials → displays the product inventory', () => {
    expectInventory();
    cy.get(loginPage.errorMessage).should('not.exist');
  });

  // Requirement R-AUTH-002; scenario AUTH-002.
  it('Reload after login → keeps the user in the inventory', () => {
    expectInventory();
    cy.reload();
    expectInventory();
  });
});
