// Generated by Cypress Author on 2026-10-05.
describe('SauceDemo login', {
  baseUrl: 'https://www.saucedemo.com',
  testIsolation: true,
}, () => {
  it('Login as standard_user → displays the inventory page', () => {
    cy.fixture('user').then(({ standardUser }) => {
      // cy.login opens the application and submits the login form.
      cy.login(standardUser.username, standardUser.password);
    });

    cy.location('pathname').should('eq', '/inventory.html');
    cy.contains('[data-test="title"]', /^Products$/).should('be.visible');
    cy.get('[data-test="inventory-list"]').should('be.visible');
    cy.get('[data-test="inventory-item"]').should('have.length.greaterThan', 0);
  });
});


