// Generated by Cypress Author on 2026-10-08.
import LoginPage from '../../pages/LoginPage.js';

describe('SauceDemo login validation and access control', {
  baseUrl: 'https://www.saucedemo.com',
  testIsolation: true,
  screenshotOnRunFailure: false,
}, () => {
  const loginPage = new LoginPage();
  const invalidCredentialsMessage = 'Epic sadface: Username and password do not match any user in this service';
  const inventoryAccessMessage = "Epic sadface: You can only access '/inventory.html' when you are logged in.";

  const expectLoginError = (message, sessionUsername = null) => {
    loginPage.errorMesagge().should('be.visible').and('have.text', message);
    cy.location('pathname').should('eq', '/');
    cy.get(loginPage.loginButton).should('be.visible');
    cy.get('[data-test="inventory-container"]').should('not.exist');
    // Compare a boolean so a failed assertion cannot print a credential value.
    cy.getCookie('session-username', { log: false }).should((cookie) => {
      const expectedSession = sessionUsername === null
        ? cookie === null
        : cookie?.value === sessionUsername;
      expect(expectedSession, 'session matches the expected authentication state').to.eq(true);
    });
  };

  const withCredentials = (callback) => {
    cy.env(['SAUCE_USER', 'SAUCE_PASSWORD']).then(({ SAUCE_USER, SAUCE_PASSWORD }) => {
      if (!SAUCE_USER || !SAUCE_PASSWORD) {
        throw new Error('Set SAUCE_USER and SAUCE_PASSWORD to a valid, unlocked SauceDemo account.');
      }
      callback(SAUCE_USER, SAUCE_PASSWORD);
    });
  };

  beforeEach(() => {
    loginPage.visit();
  });

  // Requirement R-AUTH-003; scenario AUTH-003.
  it('Submit an empty form → requires a username', () => {
    loginPage.clickLoginButton();
    expectLoginError('Epic sadface: Username is required');
  });

  // Requirement R-AUTH-003; scenario AUTH-004.
  it('Submit only a password → requires a username', () => {
    withCredentials((username, password) => {
      loginPage.enterUserpassword(password);
    });
    loginPage.clickLoginButton();
    expectLoginError('Epic sadface: Username is required');
  });

  // Requirement R-AUTH-003; scenario AUTH-005.
  it('Submit only a username → requires a password', () => {
    withCredentials((username) => {
      loginPage.enterUsername(username);
    });
    loginPage.clickLoginButton();
    expectLoginError('Epic sadface: Password is required');
  });

  // Requirement R-AUTH-004; scenario AUTH-006.
  it('Submit an unknown username → rejects login', () => {
    withCredentials((username, password) => {
      cy.LoginPom(`${username}_unknown`, password);
    });
    expectLoginError(invalidCredentialsMessage);
  });

  // Requirement R-AUTH-004; scenario AUTH-007.
  it('Submit an incorrect password → rejects login', () => {
    withCredentials((username, password) => {
      cy.LoginPom(username, `${password}_invalid`);
    });
    expectLoginError(invalidCredentialsMessage);
  });

  // Requirement R-AUTH-004; scenario AUTH-008.
  it('Submit an unknown username and incorrect password → rejects login', () => {
    withCredentials((username, password) => {
      cy.LoginPom(`${username}_unknown`, `${password}_invalid`);
    });
    expectLoginError(invalidCredentialsMessage);
  });

  // Requirement R-AUTH-005; scenario AUTH-009.
  it('Submit a locked account → denies login and inventory access', () => {
    cy.env(['SAUCE_PASSWORD']).then(({ SAUCE_PASSWORD }) => {
      if (!SAUCE_PASSWORD) {
        throw new Error('Set SAUCE_PASSWORD for the locked-account scenario.');
      }
      // SauceDemo publishes demo accounts on its login page; do not copy them into fixtures.
      cy.get('[data-test="login-credentials"]', { log: false }).then(($credentials) => {
        const lockedUsername = $credentials[0].innerText.split(/\s+/).find((value) => value.includes('locked'));
        if (!lockedUsername) {
          throw new Error('The SauceDemo login page must publish a locked demo account.');
        }
        cy.LoginPom(lockedUsername, SAUCE_PASSWORD);

        // SauceDemo sets this cookie before checking whether the user is locked.
        expectLoginError('Epic sadface: Sorry, this user has been locked out.', lockedUsername);
        cy.visit('/inventory.html', { failOnStatusCode: false });
        expectLoginError(inventoryAccessMessage, lockedUsername);
      });
    });
  });

  // Requirement R-AUTH-006; scenario AUTH-010.
  it('Open the inventory without a session → redirects to login', () => {
    cy.visit('/inventory.html', { failOnStatusCode: false });
    expectLoginError(inventoryAccessMessage);
  });
});
